apiVersion: v1
kind: Service
metadata:
  name: {{ include "observaai.gateway.fullname" . }}
  labels:
    {{- include "observaai.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.service.gateway.type }}
  ports:
    - port: {{ .Values.service.gateway.port }}
      targetPort: {{ .Values.gateway.port }}
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
